DATA_ROOT = '/home/nebula/xxy/ESAM/data/scannet200-sv/'
backend_args = None
class_names = [
    'wall',
    'floor',
    'chair',
    'table',
    'door',
    'couch',
    'cabinet',
    'shelf',
    'desk',
    'office chair',
    'bed',
    'pillow',
    'sink',
    'picture',
    'window',
    'toilet',
    'bookshelf',
    'monitor',
    'curtain',
    'book',
    'armchair',
    'coffee table',
    'box',
    'refrigerator',
    'lamp',
    'kitchen cabinet',
    'towel',
    'clothes',
    'tv',
    'nightstand',
    'counter',
    'dresser',
    'stool',
    'cushion',
    'plant',
    'ceiling',
    'bathtub',
    'end table',
    'dining table',
    'keyboard',
    'bag',
    'backpack',
    'toilet paper',
    'printer',
    'tv stand',
    'whiteboard',
    'blanket',
    'shower curtain',
    'trash can',
    'closet',
    'stairs',
    'microwave',
    'stove',
    'shoe',
    'computer tower',
    'bottle',
    'bin',
    'ottoman',
    'bench',
    'board',
    'washing machine',
    'mirror',
    'copier',
    'basket',
    'sofa chair',
    'file cabinet',
    'fan',
    'laptop',
    'shower',
    'paper',
    'person',
    'paper towel dispenser',
    'oven',
    'blinds',
    'rack',
    'plate',
    'blackboard',
    'piano',
    'suitcase',
    'rail',
    'radiator',
    'recycling bin',
    'container',
    'wardrobe',
    'soap dispenser',
    'telephone',
    'bucket',
    'clock',
    'stand',
    'light',
    'laundry basket',
    'pipe',
    'clothes dryer',
    'guitar',
    'toilet paper holder',
    'seat',
    'speaker',
    'column',
    'bicycle',
    'ladder',
    'bathroom stall',
    'shower wall',
    'cup',
    'jacket',
    'storage bin',
    'coffee maker',
    'dishwasher',
    'paper towel roll',
    'machine',
    'mat',
    'windowsill',
    'bar',
    'toaster',
    'bulletin board',
    'ironing board',
    'fireplace',
    'soap dish',
    'kitchen counter',
    'doorframe',
    'toilet paper dispenser',
    'mini fridge',
    'fire extinguisher',
    'ball',
    'hat',
    'shower curtain rod',
    'water cooler',
    'paper cutter',
    'tray',
    'shower door',
    'pillar',
    'ledge',
    'toaster oven',
    'mouse',
    'toilet seat cover dispenser',
    'furniture',
    'cart',
    'storage container',
    'scale',
    'tissue box',
    'light switch',
    'crate',
    'power outlet',
    'decoration',
    'sign',
    'projector',
    'closet door',
    'vacuum cleaner',
    'candle',
    'plunger',
    'stuffed animal',
    'headphones',
    'dish rack',
    'broom',
    'guitar case',
    'range hood',
    'dustpan',
    'hair dryer',
    'water bottle',
    'handicap bar',
    'purse',
    'vent',
    'shower floor',
    'water pitcher',
    'mailbox',
    'bowl',
    'paper bag',
    'alarm clock',
    'music stand',
    'projector screen',
    'divider',
    'laundry detergent',
    'bathroom counter',
    'object',
    'bathroom vanity',
    'closet wall',
    'laundry hamper',
    'bathroom stall door',
    'ceiling light',
    'trash bin',
    'dumbbell',
    'stair rail',
    'tube',
    'bathroom cabinet',
    'cd case',
    'closet rod',
    'coffee kettle',
    'structure',
    'shower head',
    'keyboard piano',
    'case of water bottles',
    'coat rack',
    'storage organizer',
    'folded chair',
    'fire alarm',
    'power strip',
    'calendar',
    'poster',
    'potted plant',
    'luggage',
    'mattress',
]
color_mean = (
    121.87247106275309,
    109.73306679373762,
    95.614771986258,
)
color_std = (
    72.27912483750035,
    70.2937017925937,
    68.89837699573124,
)
custom_hooks = [
    dict(after_iter=True, type='EmptyCacheHook'),
    dict(
        detailed_stats=True,
        grad_monitor_interval=50,
        log_interval=10,
        type='EnhancedTrainingHook'),
    dict(
        collect_clip_stats=True,
        collect_fusion_stats=True,
        collect_grad_norm=True,
        log_interval=20,
        type='DetailedLossMonitorHook'),
    dict(check_interval=5, type='NaNDetectionHook'),
    dict(
        prefix_replace=(
            'backbone\\.',
            'bi_encoder.backbone3d.',
        ),
        pretrained=
        '/home/nebula/xxy/ESAM/work_dirs/sv3d_scannet200_ca/best_all_ap_50%_epoch_128.pth',
        strict=False,
        submodule='bi_encoder.backbone3d',
        type='PartialLoadHook'),
]
custom_imports = dict(imports=[
    'oneformer3d',
    'oneformer3d.partial_load_hook',
    'oneformer3d.detailed_loss_hook',
    'oneformer3d.enhanced_training_hook',
])
data_prefix = dict(
    pts='points',
    pts_instance_mask='instance_mask',
    pts_semantic_mask='semantic_mask',
    sp_pts_mask='super_points')
data_root = 'data/scannet/'
dataset_type = 'ScanNet200SegDataset_'
default_hooks = dict(
    checkpoint=dict(
        _scope_='mmdet3d',
        interval=1,
        max_keep_ckpts=1,
        rule='greater',
        save_best=[
            'all_ap_50%',
        ],
        type='CheckpointHook'),
    logger=dict(
        _scope_='mmdet3d',
        interval=10,
        log_metric_by_epoch=False,
        out_suffix='.log',
        type='LoggerHook'),
    param_scheduler=dict(_scope_='mmdet3d', type='ParamSchedulerHook'),
    sampler_seed=dict(_scope_='mmdet3d', type='DistSamplerSeedHook'),
    timer=dict(_scope_='mmdet3d', type='IterTimerHook'),
    visualization=dict(_scope_='mmdet3d', type='Det3DVisualizationHook'))
default_scope = 'mmdet3d'
env_cfg = dict(
    cudnn_benchmark=True,
    dist_cfg=dict(backend='nccl'),
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0))
eval_pipeline = [
    dict(
        _scope_='mmdet3d',
        backend_args=None,
        coord_type='DEPTH',
        load_dim=6,
        shift_height=False,
        type='LoadPointsFromFile',
        use_color=True,
        use_dim=[
            0,
            1,
            2,
            3,
            4,
            5,
        ]),
    dict(_scope_='mmdet3d', color_mean=None, type='NormalizePointsColor'),
    dict(_scope_='mmdet3d', keys=[
        'points',
    ], type='Pack3DDetInputs'),
]
input_modality = dict(use_camera=False, use_lidar=True)
inst_mapping = [
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    21,
    22,
    23,
    24,
    26,
    27,
    28,
    29,
    31,
    32,
    33,
    34,
    35,
    36,
    38,
    39,
    40,
    41,
    42,
    44,
    45,
    46,
    47,
    48,
    49,
    50,
    51,
    52,
    54,
    55,
    56,
    57,
    58,
    59,
    62,
    63,
    64,
    65,
    66,
    67,
    68,
    69,
    70,
    71,
    72,
    73,
    74,
    75,
    76,
    77,
    78,
    79,
    80,
    82,
    84,
    86,
    87,
    88,
    89,
    90,
    93,
    95,
    96,
    97,
    98,
    99,
    100,
    101,
    102,
    103,
    104,
    105,
    106,
    107,
    110,
    112,
    115,
    116,
    118,
    120,
    121,
    122,
    125,
    128,
    130,
    131,
    132,
    134,
    136,
    138,
    139,
    140,
    141,
    145,
    148,
    154,
    155,
    156,
    157,
    159,
    161,
    163,
    165,
    166,
    168,
    169,
    170,
    177,
    180,
    185,
    188,
    191,
    193,
    195,
    202,
    208,
    213,
    214,
    221,
    229,
    230,
    232,
    233,
    242,
    250,
    261,
    264,
    276,
    283,
    286,
    300,
    304,
    312,
    323,
    325,
    331,
    342,
    356,
    370,
    392,
    395,
    399,
    408,
    417,
    488,
    540,
    562,
    570,
    572,
    581,
    609,
    748,
    776,
    1156,
    1163,
    1164,
    1165,
    1166,
    1167,
    1168,
    1169,
    1170,
    1171,
    1172,
    1173,
    1174,
    1175,
    1176,
    1178,
    1179,
    1180,
    1181,
    1182,
    1183,
    1184,
    1185,
    1186,
    1187,
    1188,
    1189,
    1190,
    1191,
]
label2cat = dict({
    0: 'wall',
    1: 'floor',
    10: 'bed',
    100: 'bathroom stall',
    101: 'shower wall',
    102: 'cup',
    103: 'jacket',
    104: 'storage bin',
    105: 'coffee maker',
    106: 'dishwasher',
    107: 'paper towel roll',
    108: 'machine',
    109: 'mat',
    11: 'pillow',
    110: 'windowsill',
    111: 'bar',
    112: 'toaster',
    113: 'bulletin board',
    114: 'ironing board',
    115: 'fireplace',
    116: 'soap dish',
    117: 'kitchen counter',
    118: 'doorframe',
    119: 'toilet paper dispenser',
    12: 'sink',
    120: 'mini fridge',
    121: 'fire extinguisher',
    122: 'ball',
    123: 'hat',
    124: 'shower curtain rod',
    125: 'water cooler',
    126: 'paper cutter',
    127: 'tray',
    128: 'shower door',
    129: 'pillar',
    13: 'picture',
    130: 'ledge',
    131: 'toaster oven',
    132: 'mouse',
    133: 'toilet seat cover dispenser',
    134: 'furniture',
    135: 'cart',
    136: 'storage container',
    137: 'scale',
    138: 'tissue box',
    139: 'light switch',
    14: 'window',
    140: 'crate',
    141: 'power outlet',
    142: 'decoration',
    143: 'sign',
    144: 'projector',
    145: 'closet door',
    146: 'vacuum cleaner',
    147: 'candle',
    148: 'plunger',
    149: 'stuffed animal',
    15: 'toilet',
    150: 'headphones',
    151: 'dish rack',
    152: 'broom',
    153: 'guitar case',
    154: 'range hood',
    155: 'dustpan',
    156: 'hair dryer',
    157: 'water bottle',
    158: 'handicap bar',
    159: 'purse',
    16: 'bookshelf',
    160: 'vent',
    161: 'shower floor',
    162: 'water pitcher',
    163: 'mailbox',
    164: 'bowl',
    165: 'paper bag',
    166: 'alarm clock',
    167: 'music stand',
    168: 'projector screen',
    169: 'divider',
    17: 'monitor',
    170: 'laundry detergent',
    171: 'bathroom counter',
    172: 'object',
    173: 'bathroom vanity',
    174: 'closet wall',
    175: 'laundry hamper',
    176: 'bathroom stall door',
    177: 'ceiling light',
    178: 'trash bin',
    179: 'dumbbell',
    18: 'curtain',
    180: 'stair rail',
    181: 'tube',
    182: 'bathroom cabinet',
    183: 'cd case',
    184: 'closet rod',
    185: 'coffee kettle',
    186: 'structure',
    187: 'shower head',
    188: 'keyboard piano',
    189: 'case of water bottles',
    19: 'book',
    190: 'coat rack',
    191: 'storage organizer',
    192: 'folded chair',
    193: 'fire alarm',
    194: 'power strip',
    195: 'calendar',
    196: 'poster',
    197: 'potted plant',
    198: 'luggage',
    199: 'mattress',
    2: 'chair',
    20: 'armchair',
    200: 'unlabeled',
    21: 'coffee table',
    22: 'box',
    23: 'refrigerator',
    24: 'lamp',
    25: 'kitchen cabinet',
    26: 'towel',
    27: 'clothes',
    28: 'tv',
    29: 'nightstand',
    3: 'table',
    30: 'counter',
    31: 'dresser',
    32: 'stool',
    33: 'cushion',
    34: 'plant',
    35: 'ceiling',
    36: 'bathtub',
    37: 'end table',
    38: 'dining table',
    39: 'keyboard',
    4: 'door',
    40: 'bag',
    41: 'backpack',
    42: 'toilet paper',
    43: 'printer',
    44: 'tv stand',
    45: 'whiteboard',
    46: 'blanket',
    47: 'shower curtain',
    48: 'trash can',
    49: 'closet',
    5: 'couch',
    50: 'stairs',
    51: 'microwave',
    52: 'stove',
    53: 'shoe',
    54: 'computer tower',
    55: 'bottle',
    56: 'bin',
    57: 'ottoman',
    58: 'bench',
    59: 'board',
    6: 'cabinet',
    60: 'washing machine',
    61: 'mirror',
    62: 'copier',
    63: 'basket',
    64: 'sofa chair',
    65: 'file cabinet',
    66: 'fan',
    67: 'laptop',
    68: 'shower',
    69: 'paper',
    7: 'shelf',
    70: 'person',
    71: 'paper towel dispenser',
    72: 'oven',
    73: 'blinds',
    74: 'rack',
    75: 'plate',
    76: 'blackboard',
    77: 'piano',
    78: 'suitcase',
    79: 'rail',
    8: 'desk',
    80: 'radiator',
    81: 'recycling bin',
    82: 'container',
    83: 'wardrobe',
    84: 'soap dispenser',
    85: 'telephone',
    86: 'bucket',
    87: 'clock',
    88: 'stand',
    89: 'light',
    9: 'office chair',
    90: 'laundry basket',
    91: 'pipe',
    92: 'clothes dryer',
    93: 'guitar',
    94: 'toilet paper holder',
    95: 'seat',
    96: 'speaker',
    97: 'column',
    98: 'bicycle',
    99: 'ladder'
})
launcher = 'none'
load_from = None
log_level = 'INFO'
log_processor = dict(
    _scope_='mmdet3d', by_epoch=True, type='LogProcessor', window_size=1)
metainfo = dict(
    classes=(
        'wall',
        'floor',
        'cabinet',
        'bed',
        'chair',
        'sofa',
        'table',
        'door',
        'window',
        'bookshelf',
        'picture',
        'counter',
        'desk',
        'curtain',
        'refrigerator',
        'showercurtrain',
        'toilet',
        'sink',
        'bathtub',
        'otherfurniture',
    ))
metric_meta = dict(
    classes=[
        'wall',
        'floor',
        'chair',
        'table',
        'door',
        'couch',
        'cabinet',
        'shelf',
        'desk',
        'office chair',
        'bed',
        'pillow',
        'sink',
        'picture',
        'window',
        'toilet',
        'bookshelf',
        'monitor',
        'curtain',
        'book',
        'armchair',
        'coffee table',
        'box',
        'refrigerator',
        'lamp',
        'kitchen cabinet',
        'towel',
        'clothes',
        'tv',
        'nightstand',
        'counter',
        'dresser',
        'stool',
        'cushion',
        'plant',
        'ceiling',
        'bathtub',
        'end table',
        'dining table',
        'keyboard',
        'bag',
        'backpack',
        'toilet paper',
        'printer',
        'tv stand',
        'whiteboard',
        'blanket',
        'shower curtain',
        'trash can',
        'closet',
        'stairs',
        'microwave',
        'stove',
        'shoe',
        'computer tower',
        'bottle',
        'bin',
        'ottoman',
        'bench',
        'board',
        'washing machine',
        'mirror',
        'copier',
        'basket',
        'sofa chair',
        'file cabinet',
        'fan',
        'laptop',
        'shower',
        'paper',
        'person',
        'paper towel dispenser',
        'oven',
        'blinds',
        'rack',
        'plate',
        'blackboard',
        'piano',
        'suitcase',
        'rail',
        'radiator',
        'recycling bin',
        'container',
        'wardrobe',
        'soap dispenser',
        'telephone',
        'bucket',
        'clock',
        'stand',
        'light',
        'laundry basket',
        'pipe',
        'clothes dryer',
        'guitar',
        'toilet paper holder',
        'seat',
        'speaker',
        'column',
        'bicycle',
        'ladder',
        'bathroom stall',
        'shower wall',
        'cup',
        'jacket',
        'storage bin',
        'coffee maker',
        'dishwasher',
        'paper towel roll',
        'machine',
        'mat',
        'windowsill',
        'bar',
        'toaster',
        'bulletin board',
        'ironing board',
        'fireplace',
        'soap dish',
        'kitchen counter',
        'doorframe',
        'toilet paper dispenser',
        'mini fridge',
        'fire extinguisher',
        'ball',
        'hat',
        'shower curtain rod',
        'water cooler',
        'paper cutter',
        'tray',
        'shower door',
        'pillar',
        'ledge',
        'toaster oven',
        'mouse',
        'toilet seat cover dispenser',
        'furniture',
        'cart',
        'storage container',
        'scale',
        'tissue box',
        'light switch',
        'crate',
        'power outlet',
        'decoration',
        'sign',
        'projector',
        'closet door',
        'vacuum cleaner',
        'candle',
        'plunger',
        'stuffed animal',
        'headphones',
        'dish rack',
        'broom',
        'guitar case',
        'range hood',
        'dustpan',
        'hair dryer',
        'water bottle',
        'handicap bar',
        'purse',
        'vent',
        'shower floor',
        'water pitcher',
        'mailbox',
        'bowl',
        'paper bag',
        'alarm clock',
        'music stand',
        'projector screen',
        'divider',
        'laundry detergent',
        'bathroom counter',
        'object',
        'bathroom vanity',
        'closet wall',
        'laundry hamper',
        'bathroom stall door',
        'ceiling light',
        'trash bin',
        'dumbbell',
        'stair rail',
        'tube',
        'bathroom cabinet',
        'cd case',
        'closet rod',
        'coffee kettle',
        'structure',
        'shower head',
        'keyboard piano',
        'case of water bottles',
        'coat rack',
        'storage organizer',
        'folded chair',
        'fire alarm',
        'power strip',
        'calendar',
        'poster',
        'potted plant',
        'luggage',
        'mattress',
        'unlabeled',
    ],
    ignore_index=[
        200,
    ],
    label2cat=dict({
        0: 'wall',
        1: 'floor',
        10: 'bed',
        100: 'bathroom stall',
        101: 'shower wall',
        102: 'cup',
        103: 'jacket',
        104: 'storage bin',
        105: 'coffee maker',
        106: 'dishwasher',
        107: 'paper towel roll',
        108: 'machine',
        109: 'mat',
        11: 'pillow',
        110: 'windowsill',
        111: 'bar',
        112: 'toaster',
        113: 'bulletin board',
        114: 'ironing board',
        115: 'fireplace',
        116: 'soap dish',
        117: 'kitchen counter',
        118: 'doorframe',
        119: 'toilet paper dispenser',
        12: 'sink',
        120: 'mini fridge',
        121: 'fire extinguisher',
        122: 'ball',
        123: 'hat',
        124: 'shower curtain rod',
        125: 'water cooler',
        126: 'paper cutter',
        127: 'tray',
        128: 'shower door',
        129: 'pillar',
        13: 'picture',
        130: 'ledge',
        131: 'toaster oven',
        132: 'mouse',
        133: 'toilet seat cover dispenser',
        134: 'furniture',
        135: 'cart',
        136: 'storage container',
        137: 'scale',
        138: 'tissue box',
        139: 'light switch',
        14: 'window',
        140: 'crate',
        141: 'power outlet',
        142: 'decoration',
        143: 'sign',
        144: 'projector',
        145: 'closet door',
        146: 'vacuum cleaner',
        147: 'candle',
        148: 'plunger',
        149: 'stuffed animal',
        15: 'toilet',
        150: 'headphones',
        151: 'dish rack',
        152: 'broom',
        153: 'guitar case',
        154: 'range hood',
        155: 'dustpan',
        156: 'hair dryer',
        157: 'water bottle',
        158: 'handicap bar',
        159: 'purse',
        16: 'bookshelf',
        160: 'vent',
        161: 'shower floor',
        162: 'water pitcher',
        163: 'mailbox',
        164: 'bowl',
        165: 'paper bag',
        166: 'alarm clock',
        167: 'music stand',
        168: 'projector screen',
        169: 'divider',
        17: 'monitor',
        170: 'laundry detergent',
        171: 'bathroom counter',
        172: 'object',
        173: 'bathroom vanity',
        174: 'closet wall',
        175: 'laundry hamper',
        176: 'bathroom stall door',
        177: 'ceiling light',
        178: 'trash bin',
        179: 'dumbbell',
        18: 'curtain',
        180: 'stair rail',
        181: 'tube',
        182: 'bathroom cabinet',
        183: 'cd case',
        184: 'closet rod',
        185: 'coffee kettle',
        186: 'structure',
        187: 'shower head',
        188: 'keyboard piano',
        189: 'case of water bottles',
        19: 'book',
        190: 'coat rack',
        191: 'storage organizer',
        192: 'folded chair',
        193: 'fire alarm',
        194: 'power strip',
        195: 'calendar',
        196: 'poster',
        197: 'potted plant',
        198: 'luggage',
        199: 'mattress',
        2: 'chair',
        20: 'armchair',
        200: 'unlabeled',
        21: 'coffee table',
        22: 'box',
        23: 'refrigerator',
        24: 'lamp',
        25: 'kitchen cabinet',
        26: 'towel',
        27: 'clothes',
        28: 'tv',
        29: 'nightstand',
        3: 'table',
        30: 'counter',
        31: 'dresser',
        32: 'stool',
        33: 'cushion',
        34: 'plant',
        35: 'ceiling',
        36: 'bathtub',
        37: 'end table',
        38: 'dining table',
        39: 'keyboard',
        4: 'door',
        40: 'bag',
        41: 'backpack',
        42: 'toilet paper',
        43: 'printer',
        44: 'tv stand',
        45: 'whiteboard',
        46: 'blanket',
        47: 'shower curtain',
        48: 'trash can',
        49: 'closet',
        5: 'couch',
        50: 'stairs',
        51: 'microwave',
        52: 'stove',
        53: 'shoe',
        54: 'computer tower',
        55: 'bottle',
        56: 'bin',
        57: 'ottoman',
        58: 'bench',
        59: 'board',
        6: 'cabinet',
        60: 'washing machine',
        61: 'mirror',
        62: 'copier',
        63: 'basket',
        64: 'sofa chair',
        65: 'file cabinet',
        66: 'fan',
        67: 'laptop',
        68: 'shower',
        69: 'paper',
        7: 'shelf',
        70: 'person',
        71: 'paper towel dispenser',
        72: 'oven',
        73: 'blinds',
        74: 'rack',
        75: 'plate',
        76: 'blackboard',
        77: 'piano',
        78: 'suitcase',
        79: 'rail',
        8: 'desk',
        80: 'radiator',
        81: 'recycling bin',
        82: 'container',
        83: 'wardrobe',
        84: 'soap dispenser',
        85: 'telephone',
        86: 'bucket',
        87: 'clock',
        88: 'stand',
        89: 'light',
        9: 'office chair',
        90: 'laundry basket',
        91: 'pipe',
        92: 'clothes dryer',
        93: 'guitar',
        94: 'toilet paper holder',
        95: 'seat',
        96: 'speaker',
        97: 'column',
        98: 'bicycle',
        99: 'ladder'
    }))
model = dict(
    backbone=dict(
        config=dict(
            bn_momentum=0.02, conv1_kernel_size=5, dilations=[
                1,
                1,
                1,
                1,
            ]),
        in_channels=3,
        out_channels=96,
        type='Res16UNet34C'),
    bi_encoder=dict(
        clip_num_layers=6,
        clip_pretrained=
        '/home/nebula/xxy/ESAM/data/open_clip_pytorch_model.bin',
        freeze_blocks=0,
        freeze_clip_conv1=False,
        freeze_clip_early_layers=True,
        spatial_k=16,
        type='BiFusionEncoder',
        use_amp=True,
        use_enhanced_gate=False,
        use_spatial_attention=False,
        use_tiny_sa_2d=False,
        use_tiny_sa_3d=False,
        voxel_size=0.02),
    clip_criterion=dict(
        gradient_flow_ratio=0.05,
        loss_weight=0.1,
        temperature=0.07,
        type='ClipConsCriterion'),
    criterion=dict(
        inst_criterion=dict(
            bbox_loss=dict(type='AxisAlignedIoULoss'),
            fix_dice_loss_weight=True,
            fix_mean_loss=True,
            iter_matcher=True,
            loss_weight=[
                1.0,
                0.8,
                0.6,
                0.3,
                0.0,
            ],
            matcher=dict(
                costs=[
                    dict(type='QueryClassificationCost', weight=0.5),
                    dict(type='MaskBCECost', weight=1.0),
                    dict(type='MaskDiceCost', weight=1.0),
                ],
                topk=1,
                type='SparseMatcher'),
            non_object_weight=0.05,
            num_classes=1,
            type='MixedInstanceCriterion'),
        num_semantic_classes=200,
        sem_criterion=dict(
            ignore_index=200, loss_weight=0.4,
            type='ScanNetSemanticCriterion'),
        type='ScanNetMixedCriterion'),
    data_preprocessor=dict(type='Det3DDataPreprocessor_'),
    decoder=dict(
        activation_fn='gelu',
        attn_mask=True,
        cross_attn_mode=[
            '',
            'SP',
            'SP',
            'SP',
        ],
        d_model=256,
        dropout=0.0,
        fix_attention=True,
        hidden_dim=1024,
        in_channels=256,
        iter_pred=True,
        mask_pred_mode=[
            'SP',
            'SP',
            'P',
            'P',
        ],
        num_heads=8,
        num_instance_classes=1,
        num_instance_queries=0,
        num_layers=3,
        num_semantic_classes=200,
        num_semantic_linears=1,
        num_semantic_queries=0,
        objectness_flag=False,
        share_attn_mlp=False,
        share_mask_mlp=False,
        type='ScanNetMixQueryDecoder'),
    num_classes=1,
    pool=dict(channel_proj=256, type='GeoAwarePooling'),
    query_thr=0.5,
    test_cfg=dict(
        inst_score_thr=0.0,
        matrix_nms_kernel='linear',
        nms=True,
        npoint_thr=100,
        obj_normalization=True,
        pan_score_thr=0.5,
        sp_score_thr=0.4,
        stuff_classes=[
            0,
            1,
        ],
        topk_insts=100),
    train_cfg=dict(),
    type='ScanNet200MixFormer3D',
    voxel_size=0.02)
num_instance_classes = 1
num_instance_classes_eval = 1
num_points = 8192
num_semantic_classes = 200
optim_wrapper = dict(
    accumulative_counts=4,
    clip_grad=dict(max_norm=1.0, norm_type=2),
    optimizer=dict(lr=5e-05, type='AdamW', weight_decay=0.01),
    type='OptimWrapper')
param_scheduler = dict(begin=0, end=128, power=0.9, type='PolyLR')
resume = False
sem_mapping = [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    21,
    22,
    23,
    24,
    26,
    27,
    28,
    29,
    31,
    32,
    33,
    34,
    35,
    36,
    38,
    39,
    40,
    41,
    42,
    44,
    45,
    46,
    47,
    48,
    49,
    50,
    51,
    52,
    54,
    55,
    56,
    57,
    58,
    59,
    62,
    63,
    64,
    65,
    66,
    67,
    68,
    69,
    70,
    71,
    72,
    73,
    74,
    75,
    76,
    77,
    78,
    79,
    80,
    82,
    84,
    86,
    87,
    88,
    89,
    90,
    93,
    95,
    96,
    97,
    98,
    99,
    100,
    101,
    102,
    103,
    104,
    105,
    106,
    107,
    110,
    112,
    115,
    116,
    118,
    120,
    121,
    122,
    125,
    128,
    130,
    131,
    132,
    134,
    136,
    138,
    139,
    140,
    141,
    145,
    148,
    154,
    155,
    156,
    157,
    159,
    161,
    163,
    165,
    166,
    168,
    169,
    170,
    177,
    180,
    185,
    188,
    191,
    193,
    195,
    202,
    208,
    213,
    214,
    221,
    229,
    230,
    232,
    233,
    242,
    250,
    261,
    264,
    276,
    283,
    286,
    300,
    304,
    312,
    323,
    325,
    331,
    342,
    356,
    370,
    392,
    395,
    399,
    408,
    417,
    488,
    540,
    562,
    570,
    572,
    581,
    609,
    748,
    776,
    1156,
    1163,
    1164,
    1165,
    1166,
    1167,
    1168,
    1169,
    1170,
    1171,
    1172,
    1173,
    1174,
    1175,
    1176,
    1178,
    1179,
    1180,
    1181,
    1182,
    1183,
    1184,
    1185,
    1186,
    1187,
    1188,
    1189,
    1190,
    1191,
]
test_cfg = dict(type='TestLoop')
test_dataloader = dict(
    batch_size=1,
    dataset=dict(
        _scope_='mmdet3d',
        ann_file='scannet200_sv_oneformer3d_infos_val_clip.pkl',
        backend_args=None,
        data_prefix=dict(
            pts='points',
            pts_instance_mask='instance_mask',
            pts_semantic_mask='semantic_mask',
            sp_pts_mask='super_points'),
        data_root='/home/nebula/xxy/ESAM/data/scannet200-sv/',
        ignore_index=200,
        metainfo=dict(classes=[
            'wall',
            'floor',
            'chair',
            'table',
            'door',
            'couch',
            'cabinet',
            'shelf',
            'desk',
            'office chair',
            'bed',
            'pillow',
            'sink',
            'picture',
            'window',
            'toilet',
            'bookshelf',
            'monitor',
            'curtain',
            'book',
            'armchair',
            'coffee table',
            'box',
            'refrigerator',
            'lamp',
            'kitchen cabinet',
            'towel',
            'clothes',
            'tv',
            'nightstand',
            'counter',
            'dresser',
            'stool',
            'cushion',
            'plant',
            'ceiling',
            'bathtub',
            'end table',
            'dining table',
            'keyboard',
            'bag',
            'backpack',
            'toilet paper',
            'printer',
            'tv stand',
            'whiteboard',
            'blanket',
            'shower curtain',
            'trash can',
            'closet',
            'stairs',
            'microwave',
            'stove',
            'shoe',
            'computer tower',
            'bottle',
            'bin',
            'ottoman',
            'bench',
            'board',
            'washing machine',
            'mirror',
            'copier',
            'basket',
            'sofa chair',
            'file cabinet',
            'fan',
            'laptop',
            'shower',
            'paper',
            'person',
            'paper towel dispenser',
            'oven',
            'blinds',
            'rack',
            'plate',
            'blackboard',
            'piano',
            'suitcase',
            'rail',
            'radiator',
            'recycling bin',
            'container',
            'wardrobe',
            'soap dispenser',
            'telephone',
            'bucket',
            'clock',
            'stand',
            'light',
            'laundry basket',
            'pipe',
            'clothes dryer',
            'guitar',
            'toilet paper holder',
            'seat',
            'speaker',
            'column',
            'bicycle',
            'ladder',
            'bathroom stall',
            'shower wall',
            'cup',
            'jacket',
            'storage bin',
            'coffee maker',
            'dishwasher',
            'paper towel roll',
            'machine',
            'mat',
            'windowsill',
            'bar',
            'toaster',
            'bulletin board',
            'ironing board',
            'fireplace',
            'soap dish',
            'kitchen counter',
            'doorframe',
            'toilet paper dispenser',
            'mini fridge',
            'fire extinguisher',
            'ball',
            'hat',
            'shower curtain rod',
            'water cooler',
            'paper cutter',
            'tray',
            'shower door',
            'pillar',
            'ledge',
            'toaster oven',
            'mouse',
            'toilet seat cover dispenser',
            'furniture',
            'cart',
            'storage container',
            'scale',
            'tissue box',
            'light switch',
            'crate',
            'power outlet',
            'decoration',
            'sign',
            'projector',
            'closet door',
            'vacuum cleaner',
            'candle',
            'plunger',
            'stuffed animal',
            'headphones',
            'dish rack',
            'broom',
            'guitar case',
            'range hood',
            'dustpan',
            'hair dryer',
            'water bottle',
            'handicap bar',
            'purse',
            'vent',
            'shower floor',
            'water pitcher',
            'mailbox',
            'bowl',
            'paper bag',
            'alarm clock',
            'music stand',
            'projector screen',
            'divider',
            'laundry detergent',
            'bathroom counter',
            'object',
            'bathroom vanity',
            'closet wall',
            'laundry hamper',
            'bathroom stall door',
            'ceiling light',
            'trash bin',
            'dumbbell',
            'stair rail',
            'tube',
            'bathroom cabinet',
            'cd case',
            'closet rod',
            'coffee kettle',
            'structure',
            'shower head',
            'keyboard piano',
            'case of water bottles',
            'coat rack',
            'storage organizer',
            'folded chair',
            'fire alarm',
            'power strip',
            'calendar',
            'poster',
            'potted plant',
            'luggage',
            'mattress',
        ]),
        modality=dict(use_camera=False, use_lidar=True),
        pipeline=[
            dict(
                coord_type='DEPTH',
                load_dim=6,
                shift_height=False,
                type='LoadPointsFromFile',
                use_color=True,
                use_dim=[
                    0,
                    1,
                    2,
                    3,
                    4,
                    5,
                ]),
            dict(
                data_root='/home/nebula/xxy/ESAM/data/scannet200-sv/',
                type='LoadClipFeature'),
            dict(type='LoadSingleImageFromFile'),
            dict(
                type='LoadAnnotations3D_',
                with_bbox_3d=False,
                with_label_3d=False,
                with_mask_3d=True,
                with_seg_3d=True,
                with_sp_mask_3d=True),
            dict(type='SwapChairAndFloor'),
            dict(type='PointSegClassMapping'),
            dict(
                flip=False,
                img_scale=(
                    1333,
                    800,
                ),
                pts_scale_ratio=1,
                transforms=[
                    dict(
                        clamp_range=[
                            -3.0,
                            3.0,
                        ],
                        color_mean=(
                            121.87247106275309,
                            109.73306679373762,
                            95.614771986258,
                        ),
                        color_std=(
                            72.27912483750035,
                            70.2937017925937,
                            68.89837699573124,
                        ),
                        type='NormalizePointsColor_'),
                    dict(
                        merge_non_stuff_cls=False,
                        num_classes=200,
                        stuff_classes=[
                            0,
                            1,
                        ],
                        type='AddSuperPointAnnotations'),
                ],
                type='MultiScaleFlipAug3D'),
            dict(
                keys=[
                    'points',
                    'imgs',
                    'cam_info',
                    'clip_pix',
                    'clip_global',
                    'sp_pts_mask',
                ],
                type='Pack3DDetInputs_'),
        ],
        test_mode=True,
        type='ScanNet200SegDataset_'),
    drop_last=False,
    num_workers=1,
    persistent_workers=True,
    sampler=dict(_scope_='mmdet3d', shuffle=False, type='DefaultSampler'))
test_evaluator = dict(
    _scope_='mmdet3d',
    id_offset=65536,
    inst_mapping=[
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        21,
        22,
        23,
        24,
        26,
        27,
        28,
        29,
        31,
        32,
        33,
        34,
        35,
        36,
        38,
        39,
        40,
        41,
        42,
        44,
        45,
        46,
        47,
        48,
        49,
        50,
        51,
        52,
        54,
        55,
        56,
        57,
        58,
        59,
        62,
        63,
        64,
        65,
        66,
        67,
        68,
        69,
        70,
        71,
        72,
        73,
        74,
        75,
        76,
        77,
        78,
        79,
        80,
        82,
        84,
        86,
        87,
        88,
        89,
        90,
        93,
        95,
        96,
        97,
        98,
        99,
        100,
        101,
        102,
        103,
        104,
        105,
        106,
        107,
        110,
        112,
        115,
        116,
        118,
        120,
        121,
        122,
        125,
        128,
        130,
        131,
        132,
        134,
        136,
        138,
        139,
        140,
        141,
        145,
        148,
        154,
        155,
        156,
        157,
        159,
        161,
        163,
        165,
        166,
        168,
        169,
        170,
        177,
        180,
        185,
        188,
        191,
        193,
        195,
        202,
        208,
        213,
        214,
        221,
        229,
        230,
        232,
        233,
        242,
        250,
        261,
        264,
        276,
        283,
        286,
        300,
        304,
        312,
        323,
        325,
        331,
        342,
        356,
        370,
        392,
        395,
        399,
        408,
        417,
        488,
        540,
        562,
        570,
        572,
        581,
        609,
        748,
        776,
        1156,
        1163,
        1164,
        1165,
        1166,
        1167,
        1168,
        1169,
        1170,
        1171,
        1172,
        1173,
        1174,
        1175,
        1176,
        1178,
        1179,
        1180,
        1181,
        1182,
        1183,
        1184,
        1185,
        1186,
        1187,
        1188,
        1189,
        1190,
        1191,
    ],
    metric_meta=dict(
        classes=[
            'wall',
            'floor',
            'chair',
            'table',
            'door',
            'couch',
            'cabinet',
            'shelf',
            'desk',
            'office chair',
            'bed',
            'pillow',
            'sink',
            'picture',
            'window',
            'toilet',
            'bookshelf',
            'monitor',
            'curtain',
            'book',
            'armchair',
            'coffee table',
            'box',
            'refrigerator',
            'lamp',
            'kitchen cabinet',
            'towel',
            'clothes',
            'tv',
            'nightstand',
            'counter',
            'dresser',
            'stool',
            'cushion',
            'plant',
            'ceiling',
            'bathtub',
            'end table',
            'dining table',
            'keyboard',
            'bag',
            'backpack',
            'toilet paper',
            'printer',
            'tv stand',
            'whiteboard',
            'blanket',
            'shower curtain',
            'trash can',
            'closet',
            'stairs',
            'microwave',
            'stove',
            'shoe',
            'computer tower',
            'bottle',
            'bin',
            'ottoman',
            'bench',
            'board',
            'washing machine',
            'mirror',
            'copier',
            'basket',
            'sofa chair',
            'file cabinet',
            'fan',
            'laptop',
            'shower',
            'paper',
            'person',
            'paper towel dispenser',
            'oven',
            'blinds',
            'rack',
            'plate',
            'blackboard',
            'piano',
            'suitcase',
            'rail',
            'radiator',
            'recycling bin',
            'container',
            'wardrobe',
            'soap dispenser',
            'telephone',
            'bucket',
            'clock',
            'stand',
            'light',
            'laundry basket',
            'pipe',
            'clothes dryer',
            'guitar',
            'toilet paper holder',
            'seat',
            'speaker',
            'column',
            'bicycle',
            'ladder',
            'bathroom stall',
            'shower wall',
            'cup',
            'jacket',
            'storage bin',
            'coffee maker',
            'dishwasher',
            'paper towel roll',
            'machine',
            'mat',
            'windowsill',
            'bar',
            'toaster',
            'bulletin board',
            'ironing board',
            'fireplace',
            'soap dish',
            'kitchen counter',
            'doorframe',
            'toilet paper dispenser',
            'mini fridge',
            'fire extinguisher',
            'ball',
            'hat',
            'shower curtain rod',
            'water cooler',
            'paper cutter',
            'tray',
            'shower door',
            'pillar',
            'ledge',
            'toaster oven',
            'mouse',
            'toilet seat cover dispenser',
            'furniture',
            'cart',
            'storage container',
            'scale',
            'tissue box',
            'light switch',
            'crate',
            'power outlet',
            'decoration',
            'sign',
            'projector',
            'closet door',
            'vacuum cleaner',
            'candle',
            'plunger',
            'stuffed animal',
            'headphones',
            'dish rack',
            'broom',
            'guitar case',
            'range hood',
            'dustpan',
            'hair dryer',
            'water bottle',
            'handicap bar',
            'purse',
            'vent',
            'shower floor',
            'water pitcher',
            'mailbox',
            'bowl',
            'paper bag',
            'alarm clock',
            'music stand',
            'projector screen',
            'divider',
            'laundry detergent',
            'bathroom counter',
            'object',
            'bathroom vanity',
            'closet wall',
            'laundry hamper',
            'bathroom stall door',
            'ceiling light',
            'trash bin',
            'dumbbell',
            'stair rail',
            'tube',
            'bathroom cabinet',
            'cd case',
            'closet rod',
            'coffee kettle',
            'structure',
            'shower head',
            'keyboard piano',
            'case of water bottles',
            'coat rack',
            'storage organizer',
            'folded chair',
            'fire alarm',
            'power strip',
            'calendar',
            'poster',
            'potted plant',
            'luggage',
            'mattress',
            'unlabeled',
        ],
        ignore_index=[
            200,
        ],
        label2cat=dict({
            0: 'wall',
            1: 'floor',
            10: 'bed',
            100: 'bathroom stall',
            101: 'shower wall',
            102: 'cup',
            103: 'jacket',
            104: 'storage bin',
            105: 'coffee maker',
            106: 'dishwasher',
            107: 'paper towel roll',
            108: 'machine',
            109: 'mat',
            11: 'pillow',
            110: 'windowsill',
            111: 'bar',
            112: 'toaster',
            113: 'bulletin board',
            114: 'ironing board',
            115: 'fireplace',
            116: 'soap dish',
            117: 'kitchen counter',
            118: 'doorframe',
            119: 'toilet paper dispenser',
            12: 'sink',
            120: 'mini fridge',
            121: 'fire extinguisher',
            122: 'ball',
            123: 'hat',
            124: 'shower curtain rod',
            125: 'water cooler',
            126: 'paper cutter',
            127: 'tray',
            128: 'shower door',
            129: 'pillar',
            13: 'picture',
            130: 'ledge',
            131: 'toaster oven',
            132: 'mouse',
            133: 'toilet seat cover dispenser',
            134: 'furniture',
            135: 'cart',
            136: 'storage container',
            137: 'scale',
            138: 'tissue box',
            139: 'light switch',
            14: 'window',
            140: 'crate',
            141: 'power outlet',
            142: 'decoration',
            143: 'sign',
            144: 'projector',
            145: 'closet door',
            146: 'vacuum cleaner',
            147: 'candle',
            148: 'plunger',
            149: 'stuffed animal',
            15: 'toilet',
            150: 'headphones',
            151: 'dish rack',
            152: 'broom',
            153: 'guitar case',
            154: 'range hood',
            155: 'dustpan',
            156: 'hair dryer',
            157: 'water bottle',
            158: 'handicap bar',
            159: 'purse',
            16: 'bookshelf',
            160: 'vent',
            161: 'shower floor',
            162: 'water pitcher',
            163: 'mailbox',
            164: 'bowl',
            165: 'paper bag',
            166: 'alarm clock',
            167: 'music stand',
            168: 'projector screen',
            169: 'divider',
            17: 'monitor',
            170: 'laundry detergent',
            171: 'bathroom counter',
            172: 'object',
            173: 'bathroom vanity',
            174: 'closet wall',
            175: 'laundry hamper',
            176: 'bathroom stall door',
            177: 'ceiling light',
            178: 'trash bin',
            179: 'dumbbell',
            18: 'curtain',
            180: 'stair rail',
            181: 'tube',
            182: 'bathroom cabinet',
            183: 'cd case',
            184: 'closet rod',
            185: 'coffee kettle',
            186: 'structure',
            187: 'shower head',
            188: 'keyboard piano',
            189: 'case of water bottles',
            19: 'book',
            190: 'coat rack',
            191: 'storage organizer',
            192: 'folded chair',
            193: 'fire alarm',
            194: 'power strip',
            195: 'calendar',
            196: 'poster',
            197: 'potted plant',
            198: 'luggage',
            199: 'mattress',
            2: 'chair',
            20: 'armchair',
            200: 'unlabeled',
            21: 'coffee table',
            22: 'box',
            23: 'refrigerator',
            24: 'lamp',
            25: 'kitchen cabinet',
            26: 'towel',
            27: 'clothes',
            28: 'tv',
            29: 'nightstand',
            3: 'table',
            30: 'counter',
            31: 'dresser',
            32: 'stool',
            33: 'cushion',
            34: 'plant',
            35: 'ceiling',
            36: 'bathtub',
            37: 'end table',
            38: 'dining table',
            39: 'keyboard',
            4: 'door',
            40: 'bag',
            41: 'backpack',
            42: 'toilet paper',
            43: 'printer',
            44: 'tv stand',
            45: 'whiteboard',
            46: 'blanket',
            47: 'shower curtain',
            48: 'trash can',
            49: 'closet',
            5: 'couch',
            50: 'stairs',
            51: 'microwave',
            52: 'stove',
            53: 'shoe',
            54: 'computer tower',
            55: 'bottle',
            56: 'bin',
            57: 'ottoman',
            58: 'bench',
            59: 'board',
            6: 'cabinet',
            60: 'washing machine',
            61: 'mirror',
            62: 'copier',
            63: 'basket',
            64: 'sofa chair',
            65: 'file cabinet',
            66: 'fan',
            67: 'laptop',
            68: 'shower',
            69: 'paper',
            7: 'shelf',
            70: 'person',
            71: 'paper towel dispenser',
            72: 'oven',
            73: 'blinds',
            74: 'rack',
            75: 'plate',
            76: 'blackboard',
            77: 'piano',
            78: 'suitcase',
            79: 'rail',
            8: 'desk',
            80: 'radiator',
            81: 'recycling bin',
            82: 'container',
            83: 'wardrobe',
            84: 'soap dispenser',
            85: 'telephone',
            86: 'bucket',
            87: 'clock',
            88: 'stand',
            89: 'light',
            9: 'office chair',
            90: 'laundry basket',
            91: 'pipe',
            92: 'clothes dryer',
            93: 'guitar',
            94: 'toilet paper holder',
            95: 'seat',
            96: 'speaker',
            97: 'column',
            98: 'bicycle',
            99: 'ladder'
        })),
    min_num_points=1,
    sem_mapping=[
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        21,
        22,
        23,
        24,
        26,
        27,
        28,
        29,
        31,
        32,
        33,
        34,
        35,
        36,
        38,
        39,
        40,
        41,
        42,
        44,
        45,
        46,
        47,
        48,
        49,
        50,
        51,
        52,
        54,
        55,
        56,
        57,
        58,
        59,
        62,
        63,
        64,
        65,
        66,
        67,
        68,
        69,
        70,
        71,
        72,
        73,
        74,
        75,
        76,
        77,
        78,
        79,
        80,
        82,
        84,
        86,
        87,
        88,
        89,
        90,
        93,
        95,
        96,
        97,
        98,
        99,
        100,
        101,
        102,
        103,
        104,
        105,
        106,
        107,
        110,
        112,
        115,
        116,
        118,
        120,
        121,
        122,
        125,
        128,
        130,
        131,
        132,
        134,
        136,
        138,
        139,
        140,
        141,
        145,
        148,
        154,
        155,
        156,
        157,
        159,
        161,
        163,
        165,
        166,
        168,
        169,
        170,
        177,
        180,
        185,
        188,
        191,
        193,
        195,
        202,
        208,
        213,
        214,
        221,
        229,
        230,
        232,
        233,
        242,
        250,
        261,
        264,
        276,
        283,
        286,
        300,
        304,
        312,
        323,
        325,
        331,
        342,
        356,
        370,
        392,
        395,
        399,
        408,
        417,
        488,
        540,
        562,
        570,
        572,
        581,
        609,
        748,
        776,
        1156,
        1163,
        1164,
        1165,
        1166,
        1167,
        1168,
        1169,
        1170,
        1171,
        1172,
        1173,
        1174,
        1175,
        1176,
        1178,
        1179,
        1180,
        1181,
        1182,
        1183,
        1184,
        1185,
        1186,
        1187,
        1188,
        1189,
        1190,
        1191,
    ],
    stuff_class_inds=[
        0,
        1,
    ],
    thing_class_inds=[
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23,
        24,
        25,
        26,
        27,
        28,
        29,
        30,
        31,
        32,
        33,
        34,
        35,
        36,
        37,
        38,
        39,
        40,
        41,
        42,
        43,
        44,
        45,
        46,
        47,
        48,
        49,
        50,
        51,
        52,
        53,
        54,
        55,
        56,
        57,
        58,
        59,
        60,
        61,
        62,
        63,
        64,
        65,
        66,
        67,
        68,
        69,
        70,
        71,
        72,
        73,
        74,
        75,
        76,
        77,
        78,
        79,
        80,
        81,
        82,
        83,
        84,
        85,
        86,
        87,
        88,
        89,
        90,
        91,
        92,
        93,
        94,
        95,
        96,
        97,
        98,
        99,
        100,
        101,
        102,
        103,
        104,
        105,
        106,
        107,
        108,
        109,
        110,
        111,
        112,
        113,
        114,
        115,
        116,
        117,
        118,
        119,
        120,
        121,
        122,
        123,
        124,
        125,
        126,
        127,
        128,
        129,
        130,
        131,
        132,
        133,
        134,
        135,
        136,
        137,
        138,
        139,
        140,
        141,
        142,
        143,
        144,
        145,
        146,
        147,
        148,
        149,
        150,
        151,
        152,
        153,
        154,
        155,
        156,
        157,
        158,
        159,
        160,
        161,
        162,
        163,
        164,
        165,
        166,
        167,
        168,
        169,
        170,
        171,
        172,
        173,
        174,
        175,
        176,
        177,
        178,
        179,
        180,
        181,
        182,
        183,
        184,
        185,
        186,
        187,
        188,
        189,
        190,
        191,
        192,
        193,
        194,
        195,
        196,
        197,
        198,
        199,
    ],
    type='UnifiedSegMetric')
test_pipeline = [
    dict(
        coord_type='DEPTH',
        load_dim=6,
        shift_height=False,
        type='LoadPointsFromFile',
        use_color=True,
        use_dim=[
            0,
            1,
            2,
            3,
            4,
            5,
        ]),
    dict(
        data_root='/home/nebula/xxy/ESAM/data/scannet200-sv/',
        type='LoadClipFeature'),
    dict(type='LoadSingleImageFromFile'),
    dict(
        type='LoadAnnotations3D_',
        with_bbox_3d=False,
        with_label_3d=False,
        with_mask_3d=True,
        with_seg_3d=True,
        with_sp_mask_3d=True),
    dict(type='SwapChairAndFloor'),
    dict(type='PointSegClassMapping'),
    dict(
        flip=False,
        img_scale=(
            1333,
            800,
        ),
        pts_scale_ratio=1,
        transforms=[
            dict(
                clamp_range=[
                    -3.0,
                    3.0,
                ],
                color_mean=(
                    121.87247106275309,
                    109.73306679373762,
                    95.614771986258,
                ),
                color_std=(
                    72.27912483750035,
                    70.2937017925937,
                    68.89837699573124,
                ),
                type='NormalizePointsColor_'),
            dict(
                merge_non_stuff_cls=False,
                num_classes=200,
                stuff_classes=[
                    0,
                    1,
                ],
                type='AddSuperPointAnnotations'),
        ],
        type='MultiScaleFlipAug3D'),
    dict(
        keys=[
            'points',
            'imgs',
            'cam_info',
            'clip_pix',
            'clip_global',
            'sp_pts_mask',
        ],
        type='Pack3DDetInputs_'),
]
train_cfg = dict(max_epochs=128, type='EpochBasedTrainLoop', val_interval=5)
train_dataloader = dict(
    batch_size=6,
    dataset=dict(
        _scope_='mmdet3d',
        ann_file='scannet200_sv_oneformer3d_infos_train_clip.pkl',
        backend_args=None,
        data_prefix=dict(
            pts='points',
            pts_instance_mask='instance_mask',
            pts_semantic_mask='semantic_mask',
            sp_pts_mask='super_points'),
        data_root='/home/nebula/xxy/ESAM/data/scannet200-sv/',
        ignore_index=200,
        metainfo=dict(classes=[
            'wall',
            'floor',
            'chair',
            'table',
            'door',
            'couch',
            'cabinet',
            'shelf',
            'desk',
            'office chair',
            'bed',
            'pillow',
            'sink',
            'picture',
            'window',
            'toilet',
            'bookshelf',
            'monitor',
            'curtain',
            'book',
            'armchair',
            'coffee table',
            'box',
            'refrigerator',
            'lamp',
            'kitchen cabinet',
            'towel',
            'clothes',
            'tv',
            'nightstand',
            'counter',
            'dresser',
            'stool',
            'cushion',
            'plant',
            'ceiling',
            'bathtub',
            'end table',
            'dining table',
            'keyboard',
            'bag',
            'backpack',
            'toilet paper',
            'printer',
            'tv stand',
            'whiteboard',
            'blanket',
            'shower curtain',
            'trash can',
            'closet',
            'stairs',
            'microwave',
            'stove',
            'shoe',
            'computer tower',
            'bottle',
            'bin',
            'ottoman',
            'bench',
            'board',
            'washing machine',
            'mirror',
            'copier',
            'basket',
            'sofa chair',
            'file cabinet',
            'fan',
            'laptop',
            'shower',
            'paper',
            'person',
            'paper towel dispenser',
            'oven',
            'blinds',
            'rack',
            'plate',
            'blackboard',
            'piano',
            'suitcase',
            'rail',
            'radiator',
            'recycling bin',
            'container',
            'wardrobe',
            'soap dispenser',
            'telephone',
            'bucket',
            'clock',
            'stand',
            'light',
            'laundry basket',
            'pipe',
            'clothes dryer',
            'guitar',
            'toilet paper holder',
            'seat',
            'speaker',
            'column',
            'bicycle',
            'ladder',
            'bathroom stall',
            'shower wall',
            'cup',
            'jacket',
            'storage bin',
            'coffee maker',
            'dishwasher',
            'paper towel roll',
            'machine',
            'mat',
            'windowsill',
            'bar',
            'toaster',
            'bulletin board',
            'ironing board',
            'fireplace',
            'soap dish',
            'kitchen counter',
            'doorframe',
            'toilet paper dispenser',
            'mini fridge',
            'fire extinguisher',
            'ball',
            'hat',
            'shower curtain rod',
            'water cooler',
            'paper cutter',
            'tray',
            'shower door',
            'pillar',
            'ledge',
            'toaster oven',
            'mouse',
            'toilet seat cover dispenser',
            'furniture',
            'cart',
            'storage container',
            'scale',
            'tissue box',
            'light switch',
            'crate',
            'power outlet',
            'decoration',
            'sign',
            'projector',
            'closet door',
            'vacuum cleaner',
            'candle',
            'plunger',
            'stuffed animal',
            'headphones',
            'dish rack',
            'broom',
            'guitar case',
            'range hood',
            'dustpan',
            'hair dryer',
            'water bottle',
            'handicap bar',
            'purse',
            'vent',
            'shower floor',
            'water pitcher',
            'mailbox',
            'bowl',
            'paper bag',
            'alarm clock',
            'music stand',
            'projector screen',
            'divider',
            'laundry detergent',
            'bathroom counter',
            'object',
            'bathroom vanity',
            'closet wall',
            'laundry hamper',
            'bathroom stall door',
            'ceiling light',
            'trash bin',
            'dumbbell',
            'stair rail',
            'tube',
            'bathroom cabinet',
            'cd case',
            'closet rod',
            'coffee kettle',
            'structure',
            'shower head',
            'keyboard piano',
            'case of water bottles',
            'coat rack',
            'storage organizer',
            'folded chair',
            'fire alarm',
            'power strip',
            'calendar',
            'poster',
            'potted plant',
            'luggage',
            'mattress',
        ]),
        modality=dict(use_camera=False, use_lidar=True),
        pipeline=[
            dict(
                coord_type='DEPTH',
                load_dim=6,
                shift_height=False,
                type='LoadPointsFromFile',
                use_color=True,
                use_dim=[
                    0,
                    1,
                    2,
                    3,
                    4,
                    5,
                ]),
            dict(
                data_root='/home/nebula/xxy/ESAM/data/scannet200-sv/',
                type='LoadClipFeature'),
            dict(type='LoadSingleImageFromFile'),
            dict(
                type='LoadAnnotations3D_',
                with_bbox_3d=False,
                with_label_3d=False,
                with_mask_3d=True,
                with_seg_3d=True,
                with_sp_mask_3d=True),
            dict(type='SwapChairAndFloor'),
            dict(type='PointSegClassMapping'),
            dict(
                flip_ratio_bev_horizontal=0.5,
                flip_ratio_bev_vertical=0.5,
                sync_2d=False,
                type='RandomFlip3D'),
            dict(
                rot_range=[
                    -3.14,
                    3.14,
                ],
                scale_ratio_range=[
                    0.8,
                    1.2,
                ],
                shift_height=False,
                translation_std=[
                    0.1,
                    0.1,
                    0.1,
                ],
                type='GlobalRotScaleTrans'),
            dict(
                clamp_range=[
                    -3.0,
                    3.0,
                ],
                color_mean=(
                    121.87247106275309,
                    109.73306679373762,
                    95.614771986258,
                ),
                color_std=(
                    72.27912483750035,
                    70.2937017925937,
                    68.89837699573124,
                ),
                type='NormalizePointsColor_'),
            dict(
                merge_non_stuff_cls=False,
                num_classes=200,
                stuff_classes=[
                    0,
                    1,
                ],
                type='AddSuperPointAnnotations'),
            dict(
                gran=[
                    6,
                    20,
                ],
                mag=[
                    40,
                    160,
                ],
                p=0.2,
                type='ElasticTransfrom',
                voxel_size=0.02),
            dict(
                keys=[
                    'points',
                    'imgs',
                    'cam_info',
                    'clip_pix',
                    'clip_global',
                    'gt_labels_3d',
                    'pts_semantic_mask',
                    'pts_instance_mask',
                    'sp_pts_mask',
                    'gt_sp_masks',
                    'elastic_coords',
                ],
                type='Pack3DDetInputs_'),
        ],
        scene_idxs=None,
        test_mode=False,
        type='ScanNet200SegDataset_'),
    num_workers=8,
    persistent_workers=True,
    prefetch_factor=2,
    sampler=dict(_scope_='mmdet3d', shuffle=True, type='DefaultSampler'))
train_pipeline = [
    dict(
        coord_type='DEPTH',
        load_dim=6,
        shift_height=False,
        type='LoadPointsFromFile',
        use_color=True,
        use_dim=[
            0,
            1,
            2,
            3,
            4,
            5,
        ]),
    dict(
        data_root='/home/nebula/xxy/ESAM/data/scannet200-sv/',
        type='LoadClipFeature'),
    dict(type='LoadSingleImageFromFile'),
    dict(
        type='LoadAnnotations3D_',
        with_bbox_3d=False,
        with_label_3d=False,
        with_mask_3d=True,
        with_seg_3d=True,
        with_sp_mask_3d=True),
    dict(type='SwapChairAndFloor'),
    dict(type='PointSegClassMapping'),
    dict(
        flip_ratio_bev_horizontal=0.5,
        flip_ratio_bev_vertical=0.5,
        sync_2d=False,
        type='RandomFlip3D'),
    dict(
        rot_range=[
            -3.14,
            3.14,
        ],
        scale_ratio_range=[
            0.8,
            1.2,
        ],
        shift_height=False,
        translation_std=[
            0.1,
            0.1,
            0.1,
        ],
        type='GlobalRotScaleTrans'),
    dict(
        clamp_range=[
            -3.0,
            3.0,
        ],
        color_mean=(
            121.87247106275309,
            109.73306679373762,
            95.614771986258,
        ),
        color_std=(
            72.27912483750035,
            70.2937017925937,
            68.89837699573124,
        ),
        type='NormalizePointsColor_'),
    dict(
        merge_non_stuff_cls=False,
        num_classes=200,
        stuff_classes=[
            0,
            1,
        ],
        type='AddSuperPointAnnotations'),
    dict(
        gran=[
            6,
            20,
        ],
        mag=[
            40,
            160,
        ],
        p=0.2,
        type='ElasticTransfrom',
        voxel_size=0.02),
    dict(
        keys=[
            'points',
            'imgs',
            'cam_info',
            'clip_pix',
            'clip_global',
            'gt_labels_3d',
            'pts_semantic_mask',
            'pts_instance_mask',
            'sp_pts_mask',
            'gt_sp_masks',
            'elastic_coords',
        ],
        type='Pack3DDetInputs_'),
]
tta_model = dict(_scope_='mmdet3d', type='Seg3DTTAModel')
tta_pipeline = [
    dict(
        _scope_='mmdet3d',
        backend_args=None,
        coord_type='DEPTH',
        load_dim=6,
        shift_height=False,
        type='LoadPointsFromFile',
        use_color=True,
        use_dim=[
            0,
            1,
            2,
            3,
            4,
            5,
        ]),
    dict(
        _scope_='mmdet3d',
        backend_args=None,
        type='LoadAnnotations3D',
        with_bbox_3d=False,
        with_label_3d=False,
        with_mask_3d=False,
        with_seg_3d=True),
    dict(_scope_='mmdet3d', color_mean=None, type='NormalizePointsColor'),
    dict(
        _scope_='mmdet3d',
        transforms=[
            [
                dict(
                    flip_ratio_bev_horizontal=0.0,
                    flip_ratio_bev_vertical=0.0,
                    sync_2d=False,
                    type='RandomFlip3D'),
            ],
            [
                dict(keys=[
                    'points',
                ], type='Pack3DDetInputs'),
            ],
        ],
        type='TestTimeAug'),
]
val_cfg = dict(type='ValLoop')
val_dataloader = dict(
    batch_size=1,
    dataset=dict(
        _scope_='mmdet3d',
        ann_file='scannet200_sv_oneformer3d_infos_val_clip.pkl',
        backend_args=None,
        data_prefix=dict(
            pts='points',
            pts_instance_mask='instance_mask',
            pts_semantic_mask='semantic_mask',
            sp_pts_mask='super_points'),
        data_root='/home/nebula/xxy/ESAM/data/scannet200-sv/',
        ignore_index=200,
        metainfo=dict(classes=[
            'wall',
            'floor',
            'chair',
            'table',
            'door',
            'couch',
            'cabinet',
            'shelf',
            'desk',
            'office chair',
            'bed',
            'pillow',
            'sink',
            'picture',
            'window',
            'toilet',
            'bookshelf',
            'monitor',
            'curtain',
            'book',
            'armchair',
            'coffee table',
            'box',
            'refrigerator',
            'lamp',
            'kitchen cabinet',
            'towel',
            'clothes',
            'tv',
            'nightstand',
            'counter',
            'dresser',
            'stool',
            'cushion',
            'plant',
            'ceiling',
            'bathtub',
            'end table',
            'dining table',
            'keyboard',
            'bag',
            'backpack',
            'toilet paper',
            'printer',
            'tv stand',
            'whiteboard',
            'blanket',
            'shower curtain',
            'trash can',
            'closet',
            'stairs',
            'microwave',
            'stove',
            'shoe',
            'computer tower',
            'bottle',
            'bin',
            'ottoman',
            'bench',
            'board',
            'washing machine',
            'mirror',
            'copier',
            'basket',
            'sofa chair',
            'file cabinet',
            'fan',
            'laptop',
            'shower',
            'paper',
            'person',
            'paper towel dispenser',
            'oven',
            'blinds',
            'rack',
            'plate',
            'blackboard',
            'piano',
            'suitcase',
            'rail',
            'radiator',
            'recycling bin',
            'container',
            'wardrobe',
            'soap dispenser',
            'telephone',
            'bucket',
            'clock',
            'stand',
            'light',
            'laundry basket',
            'pipe',
            'clothes dryer',
            'guitar',
            'toilet paper holder',
            'seat',
            'speaker',
            'column',
            'bicycle',
            'ladder',
            'bathroom stall',
            'shower wall',
            'cup',
            'jacket',
            'storage bin',
            'coffee maker',
            'dishwasher',
            'paper towel roll',
            'machine',
            'mat',
            'windowsill',
            'bar',
            'toaster',
            'bulletin board',
            'ironing board',
            'fireplace',
            'soap dish',
            'kitchen counter',
            'doorframe',
            'toilet paper dispenser',
            'mini fridge',
            'fire extinguisher',
            'ball',
            'hat',
            'shower curtain rod',
            'water cooler',
            'paper cutter',
            'tray',
            'shower door',
            'pillar',
            'ledge',
            'toaster oven',
            'mouse',
            'toilet seat cover dispenser',
            'furniture',
            'cart',
            'storage container',
            'scale',
            'tissue box',
            'light switch',
            'crate',
            'power outlet',
            'decoration',
            'sign',
            'projector',
            'closet door',
            'vacuum cleaner',
            'candle',
            'plunger',
            'stuffed animal',
            'headphones',
            'dish rack',
            'broom',
            'guitar case',
            'range hood',
            'dustpan',
            'hair dryer',
            'water bottle',
            'handicap bar',
            'purse',
            'vent',
            'shower floor',
            'water pitcher',
            'mailbox',
            'bowl',
            'paper bag',
            'alarm clock',
            'music stand',
            'projector screen',
            'divider',
            'laundry detergent',
            'bathroom counter',
            'object',
            'bathroom vanity',
            'closet wall',
            'laundry hamper',
            'bathroom stall door',
            'ceiling light',
            'trash bin',
            'dumbbell',
            'stair rail',
            'tube',
            'bathroom cabinet',
            'cd case',
            'closet rod',
            'coffee kettle',
            'structure',
            'shower head',
            'keyboard piano',
            'case of water bottles',
            'coat rack',
            'storage organizer',
            'folded chair',
            'fire alarm',
            'power strip',
            'calendar',
            'poster',
            'potted plant',
            'luggage',
            'mattress',
        ]),
        modality=dict(use_camera=False, use_lidar=True),
        pipeline=[
            dict(
                coord_type='DEPTH',
                load_dim=6,
                shift_height=False,
                type='LoadPointsFromFile',
                use_color=True,
                use_dim=[
                    0,
                    1,
                    2,
                    3,
                    4,
                    5,
                ]),
            dict(
                data_root='/home/nebula/xxy/ESAM/data/scannet200-sv/',
                type='LoadClipFeature'),
            dict(type='LoadSingleImageFromFile'),
            dict(
                type='LoadAnnotations3D_',
                with_bbox_3d=False,
                with_label_3d=False,
                with_mask_3d=True,
                with_seg_3d=True,
                with_sp_mask_3d=True),
            dict(type='SwapChairAndFloor'),
            dict(type='PointSegClassMapping'),
            dict(
                flip=False,
                img_scale=(
                    1333,
                    800,
                ),
                pts_scale_ratio=1,
                transforms=[
                    dict(
                        clamp_range=[
                            -3.0,
                            3.0,
                        ],
                        color_mean=(
                            121.87247106275309,
                            109.73306679373762,
                            95.614771986258,
                        ),
                        color_std=(
                            72.27912483750035,
                            70.2937017925937,
                            68.89837699573124,
                        ),
                        type='NormalizePointsColor_'),
                    dict(
                        merge_non_stuff_cls=False,
                        num_classes=200,
                        stuff_classes=[
                            0,
                            1,
                        ],
                        type='AddSuperPointAnnotations'),
                ],
                type='MultiScaleFlipAug3D'),
            dict(
                keys=[
                    'points',
                    'imgs',
                    'cam_info',
                    'clip_pix',
                    'clip_global',
                    'sp_pts_mask',
                ],
                type='Pack3DDetInputs_'),
        ],
        test_mode=True,
        type='ScanNet200SegDataset_'),
    drop_last=False,
    num_workers=1,
    persistent_workers=True,
    sampler=dict(_scope_='mmdet3d', shuffle=False, type='DefaultSampler'))
val_evaluator = dict(
    _scope_='mmdet3d',
    id_offset=65536,
    inst_mapping=[
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        21,
        22,
        23,
        24,
        26,
        27,
        28,
        29,
        31,
        32,
        33,
        34,
        35,
        36,
        38,
        39,
        40,
        41,
        42,
        44,
        45,
        46,
        47,
        48,
        49,
        50,
        51,
        52,
        54,
        55,
        56,
        57,
        58,
        59,
        62,
        63,
        64,
        65,
        66,
        67,
        68,
        69,
        70,
        71,
        72,
        73,
        74,
        75,
        76,
        77,
        78,
        79,
        80,
        82,
        84,
        86,
        87,
        88,
        89,
        90,
        93,
        95,
        96,
        97,
        98,
        99,
        100,
        101,
        102,
        103,
        104,
        105,
        106,
        107,
        110,
        112,
        115,
        116,
        118,
        120,
        121,
        122,
        125,
        128,
        130,
        131,
        132,
        134,
        136,
        138,
        139,
        140,
        141,
        145,
        148,
        154,
        155,
        156,
        157,
        159,
        161,
        163,
        165,
        166,
        168,
        169,
        170,
        177,
        180,
        185,
        188,
        191,
        193,
        195,
        202,
        208,
        213,
        214,
        221,
        229,
        230,
        232,
        233,
        242,
        250,
        261,
        264,
        276,
        283,
        286,
        300,
        304,
        312,
        323,
        325,
        331,
        342,
        356,
        370,
        392,
        395,
        399,
        408,
        417,
        488,
        540,
        562,
        570,
        572,
        581,
        609,
        748,
        776,
        1156,
        1163,
        1164,
        1165,
        1166,
        1167,
        1168,
        1169,
        1170,
        1171,
        1172,
        1173,
        1174,
        1175,
        1176,
        1178,
        1179,
        1180,
        1181,
        1182,
        1183,
        1184,
        1185,
        1186,
        1187,
        1188,
        1189,
        1190,
        1191,
    ],
    metric_meta=dict(
        classes=[
            'wall',
            'floor',
            'chair',
            'table',
            'door',
            'couch',
            'cabinet',
            'shelf',
            'desk',
            'office chair',
            'bed',
            'pillow',
            'sink',
            'picture',
            'window',
            'toilet',
            'bookshelf',
            'monitor',
            'curtain',
            'book',
            'armchair',
            'coffee table',
            'box',
            'refrigerator',
            'lamp',
            'kitchen cabinet',
            'towel',
            'clothes',
            'tv',
            'nightstand',
            'counter',
            'dresser',
            'stool',
            'cushion',
            'plant',
            'ceiling',
            'bathtub',
            'end table',
            'dining table',
            'keyboard',
            'bag',
            'backpack',
            'toilet paper',
            'printer',
            'tv stand',
            'whiteboard',
            'blanket',
            'shower curtain',
            'trash can',
            'closet',
            'stairs',
            'microwave',
            'stove',
            'shoe',
            'computer tower',
            'bottle',
            'bin',
            'ottoman',
            'bench',
            'board',
            'washing machine',
            'mirror',
            'copier',
            'basket',
            'sofa chair',
            'file cabinet',
            'fan',
            'laptop',
            'shower',
            'paper',
            'person',
            'paper towel dispenser',
            'oven',
            'blinds',
            'rack',
            'plate',
            'blackboard',
            'piano',
            'suitcase',
            'rail',
            'radiator',
            'recycling bin',
            'container',
            'wardrobe',
            'soap dispenser',
            'telephone',
            'bucket',
            'clock',
            'stand',
            'light',
            'laundry basket',
            'pipe',
            'clothes dryer',
            'guitar',
            'toilet paper holder',
            'seat',
            'speaker',
            'column',
            'bicycle',
            'ladder',
            'bathroom stall',
            'shower wall',
            'cup',
            'jacket',
            'storage bin',
            'coffee maker',
            'dishwasher',
            'paper towel roll',
            'machine',
            'mat',
            'windowsill',
            'bar',
            'toaster',
            'bulletin board',
            'ironing board',
            'fireplace',
            'soap dish',
            'kitchen counter',
            'doorframe',
            'toilet paper dispenser',
            'mini fridge',
            'fire extinguisher',
            'ball',
            'hat',
            'shower curtain rod',
            'water cooler',
            'paper cutter',
            'tray',
            'shower door',
            'pillar',
            'ledge',
            'toaster oven',
            'mouse',
            'toilet seat cover dispenser',
            'furniture',
            'cart',
            'storage container',
            'scale',
            'tissue box',
            'light switch',
            'crate',
            'power outlet',
            'decoration',
            'sign',
            'projector',
            'closet door',
            'vacuum cleaner',
            'candle',
            'plunger',
            'stuffed animal',
            'headphones',
            'dish rack',
            'broom',
            'guitar case',
            'range hood',
            'dustpan',
            'hair dryer',
            'water bottle',
            'handicap bar',
            'purse',
            'vent',
            'shower floor',
            'water pitcher',
            'mailbox',
            'bowl',
            'paper bag',
            'alarm clock',
            'music stand',
            'projector screen',
            'divider',
            'laundry detergent',
            'bathroom counter',
            'object',
            'bathroom vanity',
            'closet wall',
            'laundry hamper',
            'bathroom stall door',
            'ceiling light',
            'trash bin',
            'dumbbell',
            'stair rail',
            'tube',
            'bathroom cabinet',
            'cd case',
            'closet rod',
            'coffee kettle',
            'structure',
            'shower head',
            'keyboard piano',
            'case of water bottles',
            'coat rack',
            'storage organizer',
            'folded chair',
            'fire alarm',
            'power strip',
            'calendar',
            'poster',
            'potted plant',
            'luggage',
            'mattress',
            'unlabeled',
        ],
        ignore_index=[
            200,
        ],
        label2cat=dict({
            0: 'wall',
            1: 'floor',
            10: 'bed',
            100: 'bathroom stall',
            101: 'shower wall',
            102: 'cup',
            103: 'jacket',
            104: 'storage bin',
            105: 'coffee maker',
            106: 'dishwasher',
            107: 'paper towel roll',
            108: 'machine',
            109: 'mat',
            11: 'pillow',
            110: 'windowsill',
            111: 'bar',
            112: 'toaster',
            113: 'bulletin board',
            114: 'ironing board',
            115: 'fireplace',
            116: 'soap dish',
            117: 'kitchen counter',
            118: 'doorframe',
            119: 'toilet paper dispenser',
            12: 'sink',
            120: 'mini fridge',
            121: 'fire extinguisher',
            122: 'ball',
            123: 'hat',
            124: 'shower curtain rod',
            125: 'water cooler',
            126: 'paper cutter',
            127: 'tray',
            128: 'shower door',
            129: 'pillar',
            13: 'picture',
            130: 'ledge',
            131: 'toaster oven',
            132: 'mouse',
            133: 'toilet seat cover dispenser',
            134: 'furniture',
            135: 'cart',
            136: 'storage container',
            137: 'scale',
            138: 'tissue box',
            139: 'light switch',
            14: 'window',
            140: 'crate',
            141: 'power outlet',
            142: 'decoration',
            143: 'sign',
            144: 'projector',
            145: 'closet door',
            146: 'vacuum cleaner',
            147: 'candle',
            148: 'plunger',
            149: 'stuffed animal',
            15: 'toilet',
            150: 'headphones',
            151: 'dish rack',
            152: 'broom',
            153: 'guitar case',
            154: 'range hood',
            155: 'dustpan',
            156: 'hair dryer',
            157: 'water bottle',
            158: 'handicap bar',
            159: 'purse',
            16: 'bookshelf',
            160: 'vent',
            161: 'shower floor',
            162: 'water pitcher',
            163: 'mailbox',
            164: 'bowl',
            165: 'paper bag',
            166: 'alarm clock',
            167: 'music stand',
            168: 'projector screen',
            169: 'divider',
            17: 'monitor',
            170: 'laundry detergent',
            171: 'bathroom counter',
            172: 'object',
            173: 'bathroom vanity',
            174: 'closet wall',
            175: 'laundry hamper',
            176: 'bathroom stall door',
            177: 'ceiling light',
            178: 'trash bin',
            179: 'dumbbell',
            18: 'curtain',
            180: 'stair rail',
            181: 'tube',
            182: 'bathroom cabinet',
            183: 'cd case',
            184: 'closet rod',
            185: 'coffee kettle',
            186: 'structure',
            187: 'shower head',
            188: 'keyboard piano',
            189: 'case of water bottles',
            19: 'book',
            190: 'coat rack',
            191: 'storage organizer',
            192: 'folded chair',
            193: 'fire alarm',
            194: 'power strip',
            195: 'calendar',
            196: 'poster',
            197: 'potted plant',
            198: 'luggage',
            199: 'mattress',
            2: 'chair',
            20: 'armchair',
            200: 'unlabeled',
            21: 'coffee table',
            22: 'box',
            23: 'refrigerator',
            24: 'lamp',
            25: 'kitchen cabinet',
            26: 'towel',
            27: 'clothes',
            28: 'tv',
            29: 'nightstand',
            3: 'table',
            30: 'counter',
            31: 'dresser',
            32: 'stool',
            33: 'cushion',
            34: 'plant',
            35: 'ceiling',
            36: 'bathtub',
            37: 'end table',
            38: 'dining table',
            39: 'keyboard',
            4: 'door',
            40: 'bag',
            41: 'backpack',
            42: 'toilet paper',
            43: 'printer',
            44: 'tv stand',
            45: 'whiteboard',
            46: 'blanket',
            47: 'shower curtain',
            48: 'trash can',
            49: 'closet',
            5: 'couch',
            50: 'stairs',
            51: 'microwave',
            52: 'stove',
            53: 'shoe',
            54: 'computer tower',
            55: 'bottle',
            56: 'bin',
            57: 'ottoman',
            58: 'bench',
            59: 'board',
            6: 'cabinet',
            60: 'washing machine',
            61: 'mirror',
            62: 'copier',
            63: 'basket',
            64: 'sofa chair',
            65: 'file cabinet',
            66: 'fan',
            67: 'laptop',
            68: 'shower',
            69: 'paper',
            7: 'shelf',
            70: 'person',
            71: 'paper towel dispenser',
            72: 'oven',
            73: 'blinds',
            74: 'rack',
            75: 'plate',
            76: 'blackboard',
            77: 'piano',
            78: 'suitcase',
            79: 'rail',
            8: 'desk',
            80: 'radiator',
            81: 'recycling bin',
            82: 'container',
            83: 'wardrobe',
            84: 'soap dispenser',
            85: 'telephone',
            86: 'bucket',
            87: 'clock',
            88: 'stand',
            89: 'light',
            9: 'office chair',
            90: 'laundry basket',
            91: 'pipe',
            92: 'clothes dryer',
            93: 'guitar',
            94: 'toilet paper holder',
            95: 'seat',
            96: 'speaker',
            97: 'column',
            98: 'bicycle',
            99: 'ladder'
        })),
    min_num_points=1,
    sem_mapping=[
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        21,
        22,
        23,
        24,
        26,
        27,
        28,
        29,
        31,
        32,
        33,
        34,
        35,
        36,
        38,
        39,
        40,
        41,
        42,
        44,
        45,
        46,
        47,
        48,
        49,
        50,
        51,
        52,
        54,
        55,
        56,
        57,
        58,
        59,
        62,
        63,
        64,
        65,
        66,
        67,
        68,
        69,
        70,
        71,
        72,
        73,
        74,
        75,
        76,
        77,
        78,
        79,
        80,
        82,
        84,
        86,
        87,
        88,
        89,
        90,
        93,
        95,
        96,
        97,
        98,
        99,
        100,
        101,
        102,
        103,
        104,
        105,
        106,
        107,
        110,
        112,
        115,
        116,
        118,
        120,
        121,
        122,
        125,
        128,
        130,
        131,
        132,
        134,
        136,
        138,
        139,
        140,
        141,
        145,
        148,
        154,
        155,
        156,
        157,
        159,
        161,
        163,
        165,
        166,
        168,
        169,
        170,
        177,
        180,
        185,
        188,
        191,
        193,
        195,
        202,
        208,
        213,
        214,
        221,
        229,
        230,
        232,
        233,
        242,
        250,
        261,
        264,
        276,
        283,
        286,
        300,
        304,
        312,
        323,
        325,
        331,
        342,
        356,
        370,
        392,
        395,
        399,
        408,
        417,
        488,
        540,
        562,
        570,
        572,
        581,
        609,
        748,
        776,
        1156,
        1163,
        1164,
        1165,
        1166,
        1167,
        1168,
        1169,
        1170,
        1171,
        1172,
        1173,
        1174,
        1175,
        1176,
        1178,
        1179,
        1180,
        1181,
        1182,
        1183,
        1184,
        1185,
        1186,
        1187,
        1188,
        1189,
        1190,
        1191,
    ],
    stuff_class_inds=[
        0,
        1,
    ],
    thing_class_inds=[
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23,
        24,
        25,
        26,
        27,
        28,
        29,
        30,
        31,
        32,
        33,
        34,
        35,
        36,
        37,
        38,
        39,
        40,
        41,
        42,
        43,
        44,
        45,
        46,
        47,
        48,
        49,
        50,
        51,
        52,
        53,
        54,
        55,
        56,
        57,
        58,
        59,
        60,
        61,
        62,
        63,
        64,
        65,
        66,
        67,
        68,
        69,
        70,
        71,
        72,
        73,
        74,
        75,
        76,
        77,
        78,
        79,
        80,
        81,
        82,
        83,
        84,
        85,
        86,
        87,
        88,
        89,
        90,
        91,
        92,
        93,
        94,
        95,
        96,
        97,
        98,
        99,
        100,
        101,
        102,
        103,
        104,
        105,
        106,
        107,
        108,
        109,
        110,
        111,
        112,
        113,
        114,
        115,
        116,
        117,
        118,
        119,
        120,
        121,
        122,
        123,
        124,
        125,
        126,
        127,
        128,
        129,
        130,
        131,
        132,
        133,
        134,
        135,
        136,
        137,
        138,
        139,
        140,
        141,
        142,
        143,
        144,
        145,
        146,
        147,
        148,
        149,
        150,
        151,
        152,
        153,
        154,
        155,
        156,
        157,
        158,
        159,
        160,
        161,
        162,
        163,
        164,
        165,
        166,
        167,
        168,
        169,
        170,
        171,
        172,
        173,
        174,
        175,
        176,
        177,
        178,
        179,
        180,
        181,
        182,
        183,
        184,
        185,
        186,
        187,
        188,
        189,
        190,
        191,
        192,
        193,
        194,
        195,
        196,
        197,
        198,
        199,
    ],
    type='UnifiedSegMetric')
vis_backends = [
    dict(type='LocalVisBackend'),
]
visualizer = dict(
    _scope_='mmdet3d',
    name='visualizer',
    type='Det3DLocalVisualizer',
    vis_backends=[
        dict(type='LocalVisBackend'),
    ])
work_dir = 'work_dirs/tmp_test_projection'
